Error: Fixed some glitches for Linux & Windows
Turned out Linux would never return XT_EINVAL! This is now solved.
On Windows XT_ESOCKTNOSUPPORT is now also returned.